name: sdm
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.3.0
  device_info_plus: ^10.1.2
  flutter_spinkit: ^5.2.1
  email_validator: ^3.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.4.0
  baseflow_plugin_template: ^2.2.0
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  clipboard: ^0.1.3
  google_nav_bar: ^5.0.7
  flutter_date_pickers: ^0.4.3
  loading_animation_widget: ^1.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  provider: ^6.1.2
  syncfusion_flutter_datagrid: ^26.2.14
  multi_select_flutter: ^4.1.3
  flutter_slidable: ^4.0.0
  timezone: ^0.9.4
  dropdown_search: ^5.0.6
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.8.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"