class RouteOrganization2 {
  RouteOrganization2({
    required this.date,
    required this.zid,
    required this.townsequence,
    required this.routeNummer,
    required this.routeNamebspr,
    required this.id,
    required this.nummer,
    required this.organizationYnxtvisitdat,
    required this.organizationId,
    required this.organizationNummer,
    required this.organizationNamebspr,
    required this.organizationYcustypId,
    required this.organizationYmasonry,
    required this.organizationYgpslat,
    required this.organizationYgpslon,
    required this.organizationYwaterpr,
    required this.organizationYflooring,
    required this.organizationYassigtoSuch,
    required this.organizationYowname,
    required this.organizationYstilea,
    required this.organizationYselcolourSuch,
    required this.organizationYcustypNamebspr,
    required this.organizationYactiv,
    required this.organizationYorgowndob,
    required this.organizationYaddressl1,
    required this.organizationYaddressl2,
    required this.organizationYaddressl3,
    required this.organizationYaddressl4,
    required this.organizationYtownNamebspr,
    required this.organizationYphone1,
    required this.organizationYphone2,
    required this.organizationYemail,
    required this.organizationYwhtapp,
    required this.organizationYspaint,
    required this.organizationYswaterp,
    required this.organizationYcustypSuch,
    required this.organizationYsuporgNummer,
    required this.organizationYsuporgNamebspr,
    required this.organizationYsanmet,
    required this.organizationYvisdis,
    required this.organizationYscemet,
    required this.zn,
  });

  String date;
  String zid;
  int townsequence;
  String routeNummer;
  String routeNamebspr;
  String id;
  String nummer;
  String organizationYnxtvisitdat;
  String organizationId;
  String organizationNummer;
  String organizationNamebspr;
  String organizationYcustypId;
  bool organizationYmasonry;
  String organizationYgpslat;
  String organizationYgpslon;
  bool organizationYwaterpr;
  bool organizationYflooring;
  String organizationYassigtoSuch;
  String organizationYowname;
  bool organizationYstilea;
  String organizationYselcolourSuch;
  String organizationYcustypNamebspr;
  bool organizationYactiv;
  String organizationYorgowndob;
  String organizationYaddressl1;
  String organizationYaddressl2;
  String organizationYaddressl3;
  String organizationYaddressl4;
  String organizationYtownNamebspr;
  String organizationYphone1;
  String organizationYphone2;
  String organizationYemail;
  String organizationYwhtapp;
  bool organizationYspaint;
  bool organizationYswaterp;
  String organizationYcustypSuch;
  String organizationYsuporgNummer;
  String organizationYsuporgNamebspr;
  bool organizationYsanmet;
  int organizationYvisdis;
  bool organizationYscemet;
  int zn;

  factory RouteOrganization2.fromJson(Map<String, dynamic> json) => RouteOrganization2(
        date: json["date"],
        zid: json["zid"],
        townsequence: json["townsequence"],
        routeNummer: json["route^nummer"],
        routeNamebspr: json["route^namebspr"],
        id: json["id"],
        nummer: json["nummer"],
        organizationYnxtvisitdat: json["organization^ynxtvisitdat"],
        organizationId: json["organization^id"],
        organizationNummer: json["organization^nummer"],
        organizationNamebspr: json["organization^namebspr"],
        organizationYcustypId: json["organization^ycustyp^id"],
        organizationYmasonry: json["organization^ymasonry"],
        organizationYgpslat: json["organization^ygpslat"],
        organizationYgpslon: json["organization^ygpslon"],
        organizationYwaterpr: json["organization^ywaterpr"],
        organizationYflooring: json["organization^yflooring"],
        organizationYassigtoSuch: json["organization^yassigto^such"],
        organizationYowname: json["organization^yowname"],
        organizationYstilea: json["organization^ystilea"],
        organizationYselcolourSuch: json["organization^yselcolour^such"],
        organizationYcustypNamebspr: json["organization^ycustyp^namebspr"],
        organizationYactiv: json["organization^yactiv"],
        organizationYorgowndob: json["organization^yorgowndob"],
        organizationYaddressl1: json["organization^yaddressl1"],
        organizationYaddressl2: json["organization^yaddressl2"],
        organizationYaddressl3: json["organization^yaddressl3"],
        organizationYaddressl4: json["organization^yaddressl4"],
        organizationYtownNamebspr: json["organization^ytown^namebspr"],
        organizationYphone1: json["organization^yphone1"],
        organizationYphone2: json["organization^yphone2"],
        organizationYemail: json["organization^yemail"],
        organizationYwhtapp: json["organization^ywhtapp"],
        organizationYspaint: json["organization^yspaint"],
        organizationYswaterp: json["organization^yswaterp"],
        organizationYcustypSuch: json["organization^ycustyp^such"],
        organizationYsuporgNummer: json["organization^ysuporg^nummer"],
        organizationYsuporgNamebspr: json["organization^ysuporg^namebspr"],
        organizationYsanmet: json["organization^ysanmet"],
        organizationYvisdis: json["organization^yvisdis"],
        organizationYscemet: json["organization^yscemet"],
        zn: json["zn"],
      );

  Map<String, dynamic> toJson() => {
        "date": date,
        "zid": zid,
        "townsequence": townsequence,
        "route^nummer": routeNummer,
        "route^namebspr": routeNamebspr,
        "id": id,
        "nummer": nummer,
        "organization^ynxtvisitdat": organizationYnxtvisitdat,
        "organization^id": organizationId,
        "organization^nummer": organizationNummer,
        "organization^namebspr": organizationNamebspr,
        "organization^ycustyp^id": organizationYcustypId,
        "organization^ymasonry": organizationYmasonry,
        "organization^ygpslat": organizationYgpslat,
        "organization^ygpslon": organizationYgpslon,
        "organization^ywaterpr": organizationYwaterpr,
        "organization^yflooring": organizationYflooring,
        "organization^yassigto^such": organizationYassigtoSuch,
        "organization^yowname": organizationYowname,
        "organization^ystilea": organizationYstilea,
        "organization^yselcolour^such": organizationYselcolourSuch,
        "organization^ycustyp^namebspr": organizationYcustypNamebspr,
        "organization^yactiv": organizationYactiv,
        "organization^yorgowndob": organizationYorgowndob,
        "organization^yaddressl1": organizationYaddressl1,
        "organization^yaddressl2": organizationYaddressl2,
        "organization^yaddressl3": organizationYaddressl3,
        "organization^yaddressl4": organizationYaddressl4,
        "organization^ytown^namebspr": organizationYtownNamebspr,
        "organization^yphone1": organizationYphone1,
        "organization^yphone2": organizationYphone2,
        "organization^yemail": organizationYemail,
        "organization^ywhtapp": organizationYwhtapp,
        "organization^yspaint": organizationYspaint,
        "organization^yswaterp": organizationYswaterp,
        "organization^ycustyp^such": organizationYcustypSuch,
        "organization^ysuporg^nummer": organizationYsuporgNummer,
        "organization^ysuporg^namebspr": organizationYsuporgNamebspr,
        "organization^ysanmet": organizationYsanmet,
        "organization^yvisdis": organizationYvisdis,
        "organization^yscemet": organizationYscemet,
        "zn": zn,
      };
}
